name: piloto_backend
description: Backend API for SOS PSY Flutter app (in-memory mock)
version: 0.1.0

environment:
  sdk: ^3.5.0

dependencies:
  shelf: ^1.4.1
  shelf_router: ^1.1.4
  shelf_cors_headers: ^0.1.5
  dart_jsonwebtoken: ^2.14.0
  crypto: ^3.0.7
  email_validator: ^3.0.0

dev_dependencies:
  lints: ^4.0.0
  test: ^1.25.0
